import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Vs(),
        ]),
      ),
    );
  }
}

class Vs extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 37,
                top: 628,
                child: Container(
                  width: 320,
                  height: 97,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFC3E0FC),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(30),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 71,
                top: 637,
                child: SizedBox(
                  width: 252.92,
                  height: 80,
                  child: Text(
                    '기쁨을 나누면 두 배!\n친구 or 가족과 함께',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 20,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w500,
                      height: 2,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 469,
                child: Container(
                  width: 320,
                  height: 97,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFC3E0FC),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(30),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 91,
                top: 498,
                child: SizedBox(
                  width: 213,
                  height: 39,
                  child: Text(
                    '나 혼자로도 충분해',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 20,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w500,
                      height: 2,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 136,
                top: 351,
                child: SizedBox(
                  width: 121,
                  child: Text(
                    '여행메이트는?',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 20,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w500,
                      height: 1.10,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 309,
                top: 263,
                child: SizedBox(
                  width: 38,
                  height: 21,
                  child: Text(
                    '71%',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 20,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w500,
                      height: 1.10,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 47,
                top: 266,
                child: Container(
                  width: 250,
                  height: 18,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFD9D9D9),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(84),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 47,
                top: 266,
                child: Container(
                  width: 178,
                  height: 18,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFA791E7),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(84),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 279,
                top: 168,
                child: Container(
                  width: 81.57,
                  height: 28,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFB0BDF2),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(100),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 283,
                top: 172,
                child: SizedBox(
                  width: 74.26,
                  height: 24,
                  child: Text(
                    '6 / 7',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF393232),
                      fontSize: 25,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w500,
                      height: 0.88,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 47,
                top: 176,
                child: SizedBox(
                  width: 42,
                  height: 20,
                  child: Text(
                    'Q6.',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 25,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w500,
                      height: 0.88,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 87,
                top: 97,
                child: SizedBox(
                  width: 220,
                  height: 41,
                  child: Text(
                    '여행 성향 테스트',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 30,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w500,
                      height: 1.33,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 341,
                top: 87,
                child: Container(
                  width: 30,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 341,
                top: 79,
                child: Container(
                  width: 30,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 341,
                top: 71,
                child: Container(
                  width: 30,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 393,
                  height: 45,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 20,
                        top: 12,
                        child: Container(
                          width: 54,
                          height: 21,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(32),
                            ),
                          ),
                          child: Stack(),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 60,
                child: Container(
                  width: 39,
                  height: 39,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFFD8DADC),
                      ),
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}